import { Navbar } from "@/components/shared/navbar";
import { Footer } from "@/components/shared/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for WowTok. Read our terms and conditions for using our AI video generation platform.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="mx-auto max-w-3xl px-6 py-20">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: March 7, 2026
        </p>

        <div className="prose prose-sm mt-8 max-w-none text-muted-foreground [&_h2]:mt-8 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-foreground [&_p]:mt-3 [&_ul]:mt-2 [&_ul]:list-disc [&_ul]:pl-6">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using WowTok (&quot;Service&quot;), you agree to be
            bound by these Terms of Service. If you do not agree, do not use the
            Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            WowTok is an AI-powered platform that generates short-form videos
            from text prompts. The Service includes AI script generation, image
            generation, video rendering, voiceover synthesis, and video
            composition.
          </p>

          <h2>3. Account Registration</h2>
          <p>
            You must create an account to use the Service. You are responsible
            for maintaining the confidentiality of your account credentials. You
            must provide accurate information and are responsible for all
            activity under your account.
          </p>

          <h2>4. Subscriptions and Payments</h2>
          <ul>
            <li>The Service is offered on a monthly subscription basis.</li>
            <li>
              Payments are processed securely through Stripe. We do not store
              your payment information directly.
            </li>
            <li>
              Subscriptions automatically renew unless cancelled before the end
              of the billing period.
            </li>
            <li>
              You may cancel at any time from your dashboard. Access continues
              until the end of the current billing period.
            </li>
            <li>Refunds are handled on a case-by-case basis.</li>
          </ul>

          <h2>5. Content Ownership and License</h2>
          <ul>
            <li>
              You retain ownership of the prompts and text you provide to the
              Service.
            </li>
            <li>
              You are granted a perpetual, worldwide, non-exclusive license to
              use, modify, and distribute the videos generated by the Service
              for any lawful purpose, including commercial use.
            </li>
            <li>
              We retain the right to use anonymized, aggregated usage data to
              improve the Service.
            </li>
          </ul>

          <h2>6. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>
              Generate content that is illegal, harmful, threatening, abusive,
              defamatory, or otherwise objectionable.
            </li>
            <li>Infringe on intellectual property rights of third parties.</li>
            <li>Generate deepfake or misleading content of real persons.</li>
            <li>
              Distribute malware or engage in phishing or other fraudulent
              activities.
            </li>
            <li>
              Circumvent usage limits or attempt unauthorized access to the
              Service.
            </li>
          </ul>

          <h2>7. AI-Generated Content Disclaimer</h2>
          <p>
            Content generated by the Service is produced by AI models and may
            not always be accurate, appropriate, or free from bias. You are
            solely responsible for reviewing and approving all generated content
            before use or distribution. We do not guarantee the suitability of
            any generated content for any particular purpose.
          </p>

          <h2>8. Service Availability</h2>
          <p>
            We strive to provide reliable service but do not guarantee
            uninterrupted or error-free operation. We reserve the right to
            modify, suspend, or discontinue the Service at any time with
            reasonable notice.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, WowTok shall not be liable
            for any indirect, incidental, special, consequential, or punitive
            damages arising from your use of the Service. Our total liability
            shall not exceed the amount you paid in the twelve months preceding
            the claim.
          </p>

          <h2>10. Termination</h2>
          <p>
            We may suspend or terminate your account if you violate these Terms.
            Upon termination, your right to use the Service ceases immediately.
            Provisions that by their nature should survive termination will
            remain in effect.
          </p>

          <h2>11. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. We will notify you of
            material changes via email or through the Service. Continued use
            after changes constitutes acceptance.
          </p>

          <h2>12. Contact</h2>
          <p>
            For questions about these Terms, contact us at{" "}
            <a
              href="mailto:hello@wowtok.com"
              className="text-foreground underline"
            >
              hello@wowtok.com
            </a>
            .
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
